version: "3"
services:
  lobby:
    image: centos
    restart: always
    ports:
      - "8989:8989"
      - "9097:9097"
    working_dir: "/project"
    volumes:
      - ./project/conf:/project/conf
      - /etc/localtime:/etc/localtime:ro
      - ./project/lobby:/lobby
      - ./project/lobby.sh:/lobby.sh
      - ./project/hhdz.sh/:/hhdz.sh
    command:
      ["/lobby.sh","/hhdz.sh"]







