version: "3"
services:
  customer:
    image: centos:7
    restart: always
    ports:
      - "8087:8087"
      - "8287:8287"
    expose:
      - "8087"
    working_dir: "/app/"
    volumes:
      - ./cut-config:/app/config
      - /etc/localtime:/etc/localtime:ro
      - ./customer:/app/customer
      - ./log:/app/log
    command:
      - /bin/bash
      - -c
      - |
        /app/customer
    environment:
      - TIME:10
  system:
    image: centos:7
    restart: always
    ports:
      - "8086:8086"
    expose:
      - "8086"
    working_dir: "/app/"
    volumes:
      - ./sys-config:/app/config
      - /etc/localtime:/etc/localtime:ro
      - ./system:/app/system
      - ./log:/app/log
    command:
      - /bin/bash
      - -c
      - |
        /app/system
    environment:
      - TIME:10